//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("mash_mainModel", "sif_InviteProjectUser", "Project", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Mash_v0._3.Models.Project), "User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Mash_v0._3.Models.User))]
[assembly: EdmRelationshipAttribute("mash_mainModel", "sif_ProjectFile", "File", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Mash_v0._3.Models.File), "Project", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Mash_v0._3.Models.Project))]
[assembly: EdmRelationshipAttribute("mash_mainModel", "sif_ProjectUser", "Project", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Mash_v0._3.Models.Project), "User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Mash_v0._3.Models.User))]
[assembly: EdmRelationshipAttribute("mash_mainModel", "sif_TagFile", "File", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Mash_v0._3.Models.File), "Tag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Mash_v0._3.Models.Tag))]
[assembly: EdmRelationshipAttribute("mash_mainModel", "sif_TopicAnswer", "Message", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Mash_v0._3.Models.Message), "Message1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Mash_v0._3.Models.Message))]

#endregion

namespace Mash_v0._3.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class mash_mainEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new mash_mainEntities object using the connection string found in the 'mash_mainEntities' section of the application configuration file.
        /// </summary>
        public mash_mainEntities() : base("name=mash_mainEntities", "mash_mainEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new mash_mainEntities object.
        /// </summary>
        public mash_mainEntities(string connectionString) : base(connectionString, "mash_mainEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new mash_mainEntities object.
        /// </summary>
        public mash_mainEntities(EntityConnection connection) : base(connection, "mash_mainEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<File> File
        {
            get
            {
                if ((_File == null))
                {
                    _File = base.CreateObjectSet<File>("File");
                }
                return _File;
            }
        }
        private ObjectSet<File> _File;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Message> Message
        {
            get
            {
                if ((_Message == null))
                {
                    _Message = base.CreateObjectSet<Message>("Message");
                }
                return _Message;
            }
        }
        private ObjectSet<Message> _Message;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PrivateMessage> PrivateMessage
        {
            get
            {
                if ((_PrivateMessage == null))
                {
                    _PrivateMessage = base.CreateObjectSet<PrivateMessage>("PrivateMessage");
                }
                return _PrivateMessage;
            }
        }
        private ObjectSet<PrivateMessage> _PrivateMessage;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Project> Project
        {
            get
            {
                if ((_Project == null))
                {
                    _Project = base.CreateObjectSet<Project>("Project");
                }
                return _Project;
            }
        }
        private ObjectSet<Project> _Project;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tag> Tag
        {
            get
            {
                if ((_Tag == null))
                {
                    _Tag = base.CreateObjectSet<Tag>("Tag");
                }
                return _Tag;
            }
        }
        private ObjectSet<Tag> _Tag;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Task> Task
        {
            get
            {
                if ((_Task == null))
                {
                    _Task = base.CreateObjectSet<Task>("Task");
                }
                return _Task;
            }
        }
        private ObjectSet<Task> _Task;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> User
        {
            get
            {
                if ((_User == null))
                {
                    _User = base.CreateObjectSet<User>("User");
                }
                return _User;
            }
        }
        private ObjectSet<User> _User;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the File EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFile(File file)
        {
            base.AddObject("File", file);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Message EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMessage(Message message)
        {
            base.AddObject("Message", message);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PrivateMessage EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPrivateMessage(PrivateMessage privateMessage)
        {
            base.AddObject("PrivateMessage", privateMessage);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Project EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProject(Project project)
        {
            base.AddObject("Project", project);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tag EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTag(Tag tag)
        {
            base.AddObject("Tag", tag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Task EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTask(Task task)
        {
            base.AddObject("Task", task);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the User EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUser(User user)
        {
            base.AddObject("User", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mash_mainModel", Name="File")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class File : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new File object.
        /// </summary>
        /// <param name="idFile">Initial value of the idFile property.</param>
        /// <param name="fileName">Initial value of the fileName property.</param>
        /// <param name="path">Initial value of the path property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="idOwner">Initial value of the idOwner property.</param>
        /// <param name="dateCreated">Initial value of the dateCreated property.</param>
        /// <param name="dateUpdated">Initial value of the dateUpdated property.</param>
        public static File CreateFile(global::System.Int32 idFile, global::System.String fileName, global::System.String path, global::System.String description, global::System.Int32 idOwner, global::System.DateTime dateCreated, global::System.DateTime dateUpdated)
        {
            File file = new File();
            file.idFile = idFile;
            file.fileName = fileName;
            file.path = path;
            file.description = description;
            file.idOwner = idOwner;
            file.dateCreated = dateCreated;
            file.dateUpdated = dateUpdated;
            return file;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idFile
        {
            get
            {
                return _idFile;
            }
            set
            {
                if (_idFile != value)
                {
                    OnidFileChanging(value);
                    ReportPropertyChanging("idFile");
                    _idFile = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idFile");
                    OnidFileChanged();
                }
            }
        }
        private global::System.Int32 _idFile;
        partial void OnidFileChanging(global::System.Int32 value);
        partial void OnidFileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String fileName
        {
            get
            {
                return _fileName;
            }
            set
            {
                OnfileNameChanging(value);
                ReportPropertyChanging("fileName");
                _fileName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("fileName");
                OnfileNameChanged();
            }
        }
        private global::System.String _fileName;
        partial void OnfileNameChanging(global::System.String value);
        partial void OnfileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String path
        {
            get
            {
                return _path;
            }
            set
            {
                OnpathChanging(value);
                ReportPropertyChanging("path");
                _path = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("path");
                OnpathChanged();
            }
        }
        private global::System.String _path;
        partial void OnpathChanging(global::System.String value);
        partial void OnpathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idOwner
        {
            get
            {
                return _idOwner;
            }
            set
            {
                OnidOwnerChanging(value);
                ReportPropertyChanging("idOwner");
                _idOwner = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idOwner");
                OnidOwnerChanged();
            }
        }
        private global::System.Int32 _idOwner;
        partial void OnidOwnerChanging(global::System.Int32 value);
        partial void OnidOwnerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dateCreated
        {
            get
            {
                return _dateCreated;
            }
            set
            {
                OndateCreatedChanging(value);
                ReportPropertyChanging("dateCreated");
                _dateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateCreated");
                OndateCreatedChanged();
            }
        }
        private global::System.DateTime _dateCreated;
        partial void OndateCreatedChanging(global::System.DateTime value);
        partial void OndateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dateUpdated
        {
            get
            {
                return _dateUpdated;
            }
            set
            {
                OndateUpdatedChanging(value);
                ReportPropertyChanging("dateUpdated");
                _dateUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateUpdated");
                OndateUpdatedChanged();
            }
        }
        private global::System.DateTime _dateUpdated;
        partial void OndateUpdatedChanging(global::System.DateTime value);
        partial void OndateUpdatedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mash_mainModel", "sif_ProjectFile", "Project")]
        public EntityCollection<Project> Project
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Project>("mash_mainModel.sif_ProjectFile", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Project>("mash_mainModel.sif_ProjectFile", "Project", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mash_mainModel", "sif_TagFile", "Tag")]
        public EntityCollection<Tag> Tag
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Tag>("mash_mainModel.sif_TagFile", "Tag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Tag>("mash_mainModel.sif_TagFile", "Tag", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mash_mainModel", Name="Message")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Message : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Message object.
        /// </summary>
        /// <param name="idMessage">Initial value of the idMessage property.</param>
        /// <param name="messageHeader">Initial value of the messageHeader property.</param>
        /// <param name="messageContent">Initial value of the messageContent property.</param>
        /// <param name="dateCreated">Initial value of the dateCreated property.</param>
        /// <param name="idMessageAuthor">Initial value of the idMessageAuthor property.</param>
        /// <param name="idProject">Initial value of the idProject property.</param>
        public static Message CreateMessage(global::System.Int32 idMessage, global::System.String messageHeader, global::System.String messageContent, global::System.DateTime dateCreated, global::System.Int32 idMessageAuthor, global::System.Int32 idProject)
        {
            Message message = new Message();
            message.idMessage = idMessage;
            message.messageHeader = messageHeader;
            message.messageContent = messageContent;
            message.dateCreated = dateCreated;
            message.idMessageAuthor = idMessageAuthor;
            message.idProject = idProject;
            return message;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idMessage
        {
            get
            {
                return _idMessage;
            }
            set
            {
                if (_idMessage != value)
                {
                    OnidMessageChanging(value);
                    ReportPropertyChanging("idMessage");
                    _idMessage = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idMessage");
                    OnidMessageChanged();
                }
            }
        }
        private global::System.Int32 _idMessage;
        partial void OnidMessageChanging(global::System.Int32 value);
        partial void OnidMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String messageHeader
        {
            get
            {
                return _messageHeader;
            }
            set
            {
                OnmessageHeaderChanging(value);
                ReportPropertyChanging("messageHeader");
                _messageHeader = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("messageHeader");
                OnmessageHeaderChanged();
            }
        }
        private global::System.String _messageHeader;
        partial void OnmessageHeaderChanging(global::System.String value);
        partial void OnmessageHeaderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String messageContent
        {
            get
            {
                return _messageContent;
            }
            set
            {
                OnmessageContentChanging(value);
                ReportPropertyChanging("messageContent");
                _messageContent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("messageContent");
                OnmessageContentChanged();
            }
        }
        private global::System.String _messageContent;
        partial void OnmessageContentChanging(global::System.String value);
        partial void OnmessageContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dateCreated
        {
            get
            {
                return _dateCreated;
            }
            set
            {
                OndateCreatedChanging(value);
                ReportPropertyChanging("dateCreated");
                _dateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateCreated");
                OndateCreatedChanged();
            }
        }
        private global::System.DateTime _dateCreated;
        partial void OndateCreatedChanging(global::System.DateTime value);
        partial void OndateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idMessageAuthor
        {
            get
            {
                return _idMessageAuthor;
            }
            set
            {
                OnidMessageAuthorChanging(value);
                ReportPropertyChanging("idMessageAuthor");
                _idMessageAuthor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idMessageAuthor");
                OnidMessageAuthorChanged();
            }
        }
        private global::System.Int32 _idMessageAuthor;
        partial void OnidMessageAuthorChanging(global::System.Int32 value);
        partial void OnidMessageAuthorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idProject
        {
            get
            {
                return _idProject;
            }
            set
            {
                OnidProjectChanging(value);
                ReportPropertyChanging("idProject");
                _idProject = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idProject");
                OnidProjectChanged();
            }
        }
        private global::System.Int32 _idProject;
        partial void OnidProjectChanging(global::System.Int32 value);
        partial void OnidProjectChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mash_mainModel", "sif_TopicAnswer", "Message1")]
        public EntityCollection<Message> Message1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Message>("mash_mainModel.sif_TopicAnswer", "Message1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Message>("mash_mainModel.sif_TopicAnswer", "Message1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mash_mainModel", "sif_TopicAnswer", "Message")]
        public EntityCollection<Message> Message2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Message>("mash_mainModel.sif_TopicAnswer", "Message");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Message>("mash_mainModel.sif_TopicAnswer", "Message", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mash_mainModel", Name="PrivateMessage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PrivateMessage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PrivateMessage object.
        /// </summary>
        /// <param name="idPrivateMessage">Initial value of the idPrivateMessage property.</param>
        /// <param name="idMessageHeader">Initial value of the idMessageHeader property.</param>
        /// <param name="idMessageText">Initial value of the idMessageText property.</param>
        /// <param name="idFrom">Initial value of the idFrom property.</param>
        /// <param name="idTo">Initial value of the idTo property.</param>
        /// <param name="dateSent">Initial value of the dateSent property.</param>
        public static PrivateMessage CreatePrivateMessage(global::System.Int32 idPrivateMessage, global::System.String idMessageHeader, global::System.String idMessageText, global::System.Int32 idFrom, global::System.Int32 idTo, global::System.DateTime dateSent)
        {
            PrivateMessage privateMessage = new PrivateMessage();
            privateMessage.idPrivateMessage = idPrivateMessage;
            privateMessage.idMessageHeader = idMessageHeader;
            privateMessage.idMessageText = idMessageText;
            privateMessage.idFrom = idFrom;
            privateMessage.idTo = idTo;
            privateMessage.dateSent = dateSent;
            return privateMessage;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idPrivateMessage
        {
            get
            {
                return _idPrivateMessage;
            }
            set
            {
                if (_idPrivateMessage != value)
                {
                    OnidPrivateMessageChanging(value);
                    ReportPropertyChanging("idPrivateMessage");
                    _idPrivateMessage = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idPrivateMessage");
                    OnidPrivateMessageChanged();
                }
            }
        }
        private global::System.Int32 _idPrivateMessage;
        partial void OnidPrivateMessageChanging(global::System.Int32 value);
        partial void OnidPrivateMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String idMessageHeader
        {
            get
            {
                return _idMessageHeader;
            }
            set
            {
                OnidMessageHeaderChanging(value);
                ReportPropertyChanging("idMessageHeader");
                _idMessageHeader = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("idMessageHeader");
                OnidMessageHeaderChanged();
            }
        }
        private global::System.String _idMessageHeader;
        partial void OnidMessageHeaderChanging(global::System.String value);
        partial void OnidMessageHeaderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String idMessageText
        {
            get
            {
                return _idMessageText;
            }
            set
            {
                OnidMessageTextChanging(value);
                ReportPropertyChanging("idMessageText");
                _idMessageText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("idMessageText");
                OnidMessageTextChanged();
            }
        }
        private global::System.String _idMessageText;
        partial void OnidMessageTextChanging(global::System.String value);
        partial void OnidMessageTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idFrom
        {
            get
            {
                return _idFrom;
            }
            set
            {
                OnidFromChanging(value);
                ReportPropertyChanging("idFrom");
                _idFrom = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idFrom");
                OnidFromChanged();
            }
        }
        private global::System.Int32 _idFrom;
        partial void OnidFromChanging(global::System.Int32 value);
        partial void OnidFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTo
        {
            get
            {
                return _idTo;
            }
            set
            {
                OnidToChanging(value);
                ReportPropertyChanging("idTo");
                _idTo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idTo");
                OnidToChanged();
            }
        }
        private global::System.Int32 _idTo;
        partial void OnidToChanging(global::System.Int32 value);
        partial void OnidToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dateSent
        {
            get
            {
                return _dateSent;
            }
            set
            {
                OndateSentChanging(value);
                ReportPropertyChanging("dateSent");
                _dateSent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateSent");
                OndateSentChanged();
            }
        }
        private global::System.DateTime _dateSent;
        partial void OndateSentChanging(global::System.DateTime value);
        partial void OndateSentChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mash_mainModel", Name="Project")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Project : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Project object.
        /// </summary>
        /// <param name="idProject">Initial value of the idProject property.</param>
        /// <param name="projectName">Initial value of the projectName property.</param>
        /// <param name="dateCreated">Initial value of the dateCreated property.</param>
        /// <param name="idOwner">Initial value of the idOwner property.</param>
        public static Project CreateProject(global::System.Int32 idProject, global::System.String projectName, global::System.DateTime dateCreated, global::System.Int32 idOwner)
        {
            Project project = new Project();
            project.idProject = idProject;
            project.projectName = projectName;
            project.dateCreated = dateCreated;
            project.idOwner = idOwner;
            return project;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idProject
        {
            get
            {
                return _idProject;
            }
            set
            {
                if (_idProject != value)
                {
                    OnidProjectChanging(value);
                    ReportPropertyChanging("idProject");
                    _idProject = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idProject");
                    OnidProjectChanged();
                }
            }
        }
        private global::System.Int32 _idProject;
        partial void OnidProjectChanging(global::System.Int32 value);
        partial void OnidProjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String projectName
        {
            get
            {
                return _projectName;
            }
            set
            {
                OnprojectNameChanging(value);
                ReportPropertyChanging("projectName");
                _projectName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("projectName");
                OnprojectNameChanged();
            }
        }
        private global::System.String _projectName;
        partial void OnprojectNameChanging(global::System.String value);
        partial void OnprojectNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dateCreated
        {
            get
            {
                return _dateCreated;
            }
            set
            {
                OndateCreatedChanging(value);
                ReportPropertyChanging("dateCreated");
                _dateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateCreated");
                OndateCreatedChanged();
            }
        }
        private global::System.DateTime _dateCreated;
        partial void OndateCreatedChanging(global::System.DateTime value);
        partial void OndateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idOwner
        {
            get
            {
                return _idOwner;
            }
            set
            {
                OnidOwnerChanging(value);
                ReportPropertyChanging("idOwner");
                _idOwner = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idOwner");
                OnidOwnerChanged();
            }
        }
        private global::System.Int32 _idOwner;
        partial void OnidOwnerChanging(global::System.Int32 value);
        partial void OnidOwnerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mash_mainModel", "sif_InviteProjectUser", "User")]
        public EntityCollection<User> User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User>("mash_mainModel.sif_InviteProjectUser", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User>("mash_mainModel.sif_InviteProjectUser", "User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mash_mainModel", "sif_ProjectFile", "File")]
        public EntityCollection<File> File
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<File>("mash_mainModel.sif_ProjectFile", "File");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<File>("mash_mainModel.sif_ProjectFile", "File", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mash_mainModel", "sif_ProjectUser", "User")]
        public EntityCollection<User> User1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User>("mash_mainModel.sif_ProjectUser", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User>("mash_mainModel.sif_ProjectUser", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mash_mainModel", Name="Tag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tag object.
        /// </summary>
        /// <param name="idTag">Initial value of the idTag property.</param>
        /// <param name="tagName">Initial value of the tagName property.</param>
        public static Tag CreateTag(global::System.Int32 idTag, global::System.String tagName)
        {
            Tag tag = new Tag();
            tag.idTag = idTag;
            tag.tagName = tagName;
            return tag;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTag
        {
            get
            {
                return _idTag;
            }
            set
            {
                if (_idTag != value)
                {
                    OnidTagChanging(value);
                    ReportPropertyChanging("idTag");
                    _idTag = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idTag");
                    OnidTagChanged();
                }
            }
        }
        private global::System.Int32 _idTag;
        partial void OnidTagChanging(global::System.Int32 value);
        partial void OnidTagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tagName
        {
            get
            {
                return _tagName;
            }
            set
            {
                OntagNameChanging(value);
                ReportPropertyChanging("tagName");
                _tagName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tagName");
                OntagNameChanged();
            }
        }
        private global::System.String _tagName;
        partial void OntagNameChanging(global::System.String value);
        partial void OntagNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mash_mainModel", "sif_TagFile", "File")]
        public EntityCollection<File> File
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<File>("mash_mainModel.sif_TagFile", "File");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<File>("mash_mainModel.sif_TagFile", "File", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mash_mainModel", Name="Task")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Task : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Task object.
        /// </summary>
        /// <param name="idTask">Initial value of the idTask property.</param>
        public static Task CreateTask(global::System.Int32 idTask)
        {
            Task task = new Task();
            task.idTask = idTask;
            return task;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTask
        {
            get
            {
                return _idTask;
            }
            set
            {
                if (_idTask != value)
                {
                    OnidTaskChanging(value);
                    ReportPropertyChanging("idTask");
                    _idTask = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idTask");
                    OnidTaskChanged();
                }
            }
        }
        private global::System.Int32 _idTask;
        partial void OnidTaskChanging(global::System.Int32 value);
        partial void OnidTaskChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String taskHeader
        {
            get
            {
                return _taskHeader;
            }
            set
            {
                OntaskHeaderChanging(value);
                ReportPropertyChanging("taskHeader");
                _taskHeader = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("taskHeader");
                OntaskHeaderChanged();
            }
        }
        private global::System.String _taskHeader;
        partial void OntaskHeaderChanging(global::System.String value);
        partial void OntaskHeaderChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mash_mainModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="idUser">Initial value of the idUser property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="firstname">Initial value of the firstname property.</param>
        /// <param name="lastname">Initial value of the lastname property.</param>
        /// <param name="dateRegistered">Initial value of the dateRegistered property.</param>
        /// <param name="dateLastVisited">Initial value of the dateLastVisited property.</param>
        /// <param name="password">Initial value of the password property.</param>
        public static User CreateUser(global::System.Int32 idUser, global::System.String email, global::System.String firstname, global::System.String lastname, global::System.DateTime dateRegistered, global::System.DateTime dateLastVisited, global::System.String password)
        {
            User user = new User();
            user.idUser = idUser;
            user.email = email;
            user.firstname = firstname;
            user.lastname = lastname;
            user.dateRegistered = dateRegistered;
            user.dateLastVisited = dateLastVisited;
            user.password = password;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idUser
        {
            get
            {
                return _idUser;
            }
            set
            {
                if (_idUser != value)
                {
                    OnidUserChanging(value);
                    ReportPropertyChanging("idUser");
                    _idUser = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idUser");
                    OnidUserChanged();
                }
            }
        }
        private global::System.Int32 _idUser;
        partial void OnidUserChanging(global::System.Int32 value);
        partial void OnidUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firstname
        {
            get
            {
                return _firstname;
            }
            set
            {
                OnfirstnameChanging(value);
                ReportPropertyChanging("firstname");
                _firstname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("firstname");
                OnfirstnameChanged();
            }
        }
        private global::System.String _firstname;
        partial void OnfirstnameChanging(global::System.String value);
        partial void OnfirstnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lastname
        {
            get
            {
                return _lastname;
            }
            set
            {
                OnlastnameChanging(value);
                ReportPropertyChanging("lastname");
                _lastname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lastname");
                OnlastnameChanged();
            }
        }
        private global::System.String _lastname;
        partial void OnlastnameChanging(global::System.String value);
        partial void OnlastnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dateRegistered
        {
            get
            {
                return _dateRegistered;
            }
            set
            {
                OndateRegisteredChanging(value);
                ReportPropertyChanging("dateRegistered");
                _dateRegistered = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateRegistered");
                OndateRegisteredChanged();
            }
        }
        private global::System.DateTime _dateRegistered;
        partial void OndateRegisteredChanging(global::System.DateTime value);
        partial void OndateRegisteredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dateLastVisited
        {
            get
            {
                return _dateLastVisited;
            }
            set
            {
                OndateLastVisitedChanging(value);
                ReportPropertyChanging("dateLastVisited");
                _dateLastVisited = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateLastVisited");
                OndateLastVisitedChanged();
            }
        }
        private global::System.DateTime _dateLastVisited;
        partial void OndateLastVisitedChanging(global::System.DateTime value);
        partial void OndateLastVisitedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> isVIP
        {
            get
            {
                return _isVIP;
            }
            set
            {
                OnisVIPChanging(value);
                ReportPropertyChanging("isVIP");
                _isVIP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isVIP");
                OnisVIPChanged();
            }
        }
        private Nullable<global::System.Boolean> _isVIP;
        partial void OnisVIPChanging(Nullable<global::System.Boolean> value);
        partial void OnisVIPChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mash_mainModel", "sif_InviteProjectUser", "Project")]
        public EntityCollection<Project> Project
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Project>("mash_mainModel.sif_InviteProjectUser", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Project>("mash_mainModel.sif_InviteProjectUser", "Project", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mash_mainModel", "sif_ProjectUser", "Project")]
        public EntityCollection<Project> Project1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Project>("mash_mainModel.sif_ProjectUser", "Project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Project>("mash_mainModel.sif_ProjectUser", "Project", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
